Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Shared Intrastructure Details"
        Parameters:
          - VPCID
          - PUBLICRT
          - PRIVATERTA
          - PRIVATERTB
          - APPBucketURL
      -
        Label:
          default: "App Environment Networking"
        Parameters:
          - APPPublicCIDRA
          - APPPublicCIDRB
          - APPPrivateCIDRA
          - APPPrivateCIDRB
      - Label:
          default: "App Environment Configuration"
        Parameters:
          - ENVIRONMENT
          - APPVERSION
    ParameterLabels:
      VPCID:
        default: "VPC to deploy into"

Parameters:
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Shared Infrastructure VPC to use
  PUBLICRT:
    Type: String
    Description: Shared Infrastructure Public Route Table
  PRIVATERTA:
    Type: String
    Description: Shared Infrastructure Private Route Table - A
  PRIVATERTB:
    Type: String
    Description: Shared Infrastructure Private Route Table - B
  APPVERSION:
    Type: String
    Description: Application Version to Deploy
  APPBucketURL:
    Type: String
    Description: Application Bucket Location
  ENVIRONMENT:
    Type: String
    Description: Type of envrionment to provision
    Default: DEV
    AllowedValues:
      - DEV
      - TEST
      - PROD
      - PRESALES
  APPPublicCIDRA:
    Type: String
    Description: CIDR to use for public subnet A for app environment
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22
  APPPublicCIDRB:
    Type: String
    Description: CIDR to use for public subnet B for app environment
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22
  APPPrivateCIDRA:
    Type: String
    Description: CIDR to use for public subnet A for app environment
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22
  APPPrivateCIDRB:
    Type: String
    Description: CIDR to use for public subnet B for app environment
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22

Mappings:
  RegionMap:
    us-east-1:
      "AmazonLinux2": "ami-0323c3dd2da7fb37d"
    us-east-2:
      "AmazonLinux2": "ami-0f7919c33c90f5b58"
    us-west-1:
      "AmazonLinux2": "ami-06fcc1f0bc2c8943f"
    us-west-2:
      "AmazonLinux2": "ami-0d6621c01e8c2de2c"
  InstanceSize:
    DEV:
      "EC2": "t2.micro"
    TEST:
      "EC2": "t2.micro"
    PROD:
      "EC2": "t2.samll"
    PRESALES:
      "EC2": "t2.micro"

Resources:
  SubnetPublicA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref APPPublicCIDRA
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPCID
  SubnetPublicB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: !Ref APPPublicCIDRB
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPCID
  SubnetPrivateA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref APPPrivateCIDRA
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPCID
  SubnetPrivateB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: !Ref APPPrivateCIDRB
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPCID
  SubnetRouteTableAssociatePublicA:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PUBLICRT
      SubnetId: !Ref SubnetPublicA
  SubnetRouteTableAssociatePublicB:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PUBLICRT
      SubnetId: !Ref SubnetPublicB
  SubnetRouteTableAssociatePrivateA:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PRIVATERTA
      SubnetId: !Ref SubnetPrivateA
  SubnetRouteTableAssociatePrivateB:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PRIVATERTB
      SubnetId: !Ref SubnetPrivateB
  EC2:
    Type: "AWS::EC2::Instance"
    DeletionPolicy: Delete
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AmazonLinux2]
      InstanceType: !FindInMap [InstanceSize, !Ref ENVIRONMENT, EC2]
      KeyName: jobca-oregon
      SecurityGroupIds:
        - !Ref SG
      SubnetId: !Ref SubnetPublicA
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y
            yum update -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets www --region ${AWS::Region}
            curl 127.0.0.1/app.php | grep -f /var/www/html/test.pattern
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          www:
            - "configure_cfn"
            - "install_www"
            - "config_app"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets www --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=5
              mode: "000400"
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"
        install_www:
          packages:
            yum:
              httpd: []
              php: []
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
        config_app:
          sources:
            /var/www/html: !Join ["",[!Ref APPBucketURL, "/App", !Ref APPVERSION, ".zip"]]
          files:
            /var/www/html/test.pattern.zip:
              source: !Join ["",[!Ref APPBucketURL, "/Test", !Ref APPVERSION, ".zip"]]
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            unzippattern:
              cwd: "/var/www/html"
              command: "unzip -o test.pattern.zip"               
  SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Join ["", ["Stack ", !Ref "AWS::StackId", " Application V", !Ref APPVERSION, " - ", !Ref ENVIRONMENT]]
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        -
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
        -
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: "-1"
          ToPort: "-1"
  ELB:
    Type: "AWS::ElasticLoadBalancing::LoadBalancer"
    Properties:
      CrossZone: true
      Instances:
        - !Ref EC2
      Listeners:
        -
          InstancePort: "80"
          InstanceProtocol: HTTP
          LoadBalancerPort: "80"
          Protocol: HTTP
      Subnets:
        - !Ref SubnetPublicA
        - !Ref SubnetPublicB
      SecurityGroups:
        - !Ref SG

Outputs:
  Endpoint:
    Description: Application Address
    Value: !Join ["", ["http://", !GetAtt ELB.DNSName, "/app.php"]]
