Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0fc61db8544a617ed
    us-east-2:
      AMI: ami-0e01ce4ee18447327
    us-west-1:
      AMI: ami-09a7fe78668f1e2c0
    us-west-2:
      AMI: ami-0ce21b51cb31a48b8
    ca-central-1:
      AMI: ami-0bf54ac1b628cf143

Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId:
        !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - AMI
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
