Resources:
  DB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: 1qaz2wsx
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0d6621c01e8c2de2c # Amazon Linux 2 in Oregon
      InstanceType: t2.micro
  S3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: wp-clivetw
