Parameters:
  EnvironmentSize:
    Description: "Select Environment Size (S, M, L)"
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
  DatabaseName:
    Type: String
    Default: wordpress
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  DatabaseUser:
    Type: String
    Default: wordpress
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  DatabasePassword:
    Type: String
    Default: 1qaz2wsx
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
  SnapToRestore:
    Description: "Snapshot id to restore"
    Type: String
    Default: ""
  TestString:
    Type: String
    Default: "Test cfn-hup and cfn-init"

Conditions:
  isLarge:
    !Equals [!Ref EnvironmentSize, "LARGE"]
  isntLarge:
    !Not [!Equals [!Ref EnvironmentSize, "LARGE"]]
  isRestore:
    !Not [!Equals [!Ref SnapToRestore, ""]]

Mappings:
  RegionMap:
    us-east-1:
      AmazonLinux2: ami-0fc61db8544a617ed
    us-east-2:
      AmazonLinux2: ami-0e01ce4ee18447327
    us-west-1:
      AmazonLinux2: ami-09a7fe78668f1e2c0
    us-west-2:
      AmazonLinux2: ami-0ce21b51cb31a48b8
    ca-central-1:
      AmazonLinux2: ami-0bf54ac1b628cf143
  InstanceSize:
    SMALL:
      EC2: t2.micro
      DB: db.t2.micro
    MEDIUM:
      EC2: t2.small
      DB: db.t2.small
    LARGE:
      EC2: t2.medium
      DB: db.t2.medium          

Resources:
  DB:
    Condition: isntLarge  # Only created if EnvironmentSize is SMALL or MEDIUM
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB]
      DBName: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseName]
      Engine: MySQL
      MasterUsername: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseUser]
      MasterUserPassword: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabasePassword]
      DBSnapshotIdentifier: !If [isRestore, !Ref SnapToRestore, !Ref "AWS::NoValue"]  # If empty or non exist, AWS will create a brand new RDS
    DeletionPolicy: Snapshot
  DBAuroraCluster:
    Condition: isLarge  # Only created if EnvironmentSize is LARGE
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseName]
      Engine: aurora
      MasterUsername: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabaseUser]
      MasterUserPassword: !If [isRestore, !Ref "AWS::NoValue", !Ref DatabasePassword]
      SnapshotIdentifier: !If [isRestore, !Ref SnapToRestore, !Ref "AWS::NoValue"]  # If empty or non exist, AWS will create a brand new RDS
    DeletionPolicy: Snapshot
  DBAurora:
    Condition: isLarge  # Only created if EnvironmentSize is LARGE
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBClusterIdentifier: !Ref DBAuroraCluster
      Engine: aurora
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB]
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region',  AmazonLinux2]
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: jobca-virginia
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash
            yum install aws-cfn-bootstrap -y
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets wordpress --region ${AWS::Region}
            yum update -y
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Count: "1"
        Timeout: PT3M
    DeletionPolicy: Delete
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          wordpress:
            - "configure_cfn"
            - "install_wordpress"
            - "config_wordpress"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets wordpress --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=5
              mode: "000400"
              owner: root
              group: root
            /var/www/html/index2.html:
              content: !Ref TestString
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"
        install_wordpress:
          packages:
            yum:
              httpd: []
              mariadb: []
          sources:
            /var/www/html: "https://wordpress.org/latest.tar.gz"
          commands:
            01_install_php74:
              command: "amazon-linux-extras install php7.4"
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
        config_wordpress:
          commands:
            01_clone_config:
              cwd: "/var/www/html/wordpress"
              test: "test ! -e /var/www/html/wordpress/wp-config.php"
              command: " cp wp-config-sample.php wp-config.php"
            02_inject_dbhost:
              cwd: "/var/www/html/wordpress"
              command: !If
                - isntLarge
                - !Sub |
                  sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
                - !Sub |
                  sed -i 's/localhost/${DBAuroraCluster.Endpoint.Address}/g' wp-config.php
            03_inject_dbname:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            04_inject_dbuser:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            05_inject_dbpassword:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
            06_store_instance_ip:
              cwd: "/var/www/html/wordpress"
              command: "curl http://169.254.169.254/latest/meta-data/public-ipv4 > ip.address"
            07a_inject_IP_1:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "define('WP_SITEURL', 'http://${!myip}/wordpress');" >> wp-config.php
            07b_inject_IP_2:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "define('WP_HOME', 'http://${!myip}/wordpress');" >> wp-config.php
            08a_inject_IP_1:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "update_option('siteurl', 'http://${!myip}/wordpress');" >> wp-content/themes/twentyseventeen/functions.php
            08a_inject_IP_2:
              cwd: "/var/www/html/wordpress"
              command: !Sub |
                myip=`cat ip.address` && echo "update_option('home', 'http://${!myip}/wordpress');" >> wp-content/themes/twentyseventeen/functions.php
  S3:
    Type: 'AWS::S3::Bucket'  # AWS names the bucket based by the stack name with random string
    DeletionPolicy: Retain

Outputs:
  wproot:
    Description: "Access URL for wordpress"
    Value: !Join ["", ["http://", !GetAtt EC2.PublicIp, "/wordpress"]]
  wpadmin:
    Description: "Admin Login URL"
    Value: !Join ["", ["http://", !GetAtt EC2.PublicIp, "/wordpress/wp-login.php"]]
