Parameters:
  EnvironmentSize:
    Description: "Select Environment Size (S, M, L)"
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: 1qaz2wsx
    NoEcho: true

Mappings:
  RegionMap:
    us-east-1:
      AmazonLinux2: ami-0fc61db8544a617ed
    us-east-2:
      AmazonLinux2: ami-0e01ce4ee18447327
    us-west-1:
      AmazonLinux2: ami-09a7fe78668f1e2c0
    us-west-2:
      AmazonLinux2: ami-0ce21b51cb31a48b8
    ca-central-1:
      AmazonLinux2: ami-0bf54ac1b628cf143
  InstanceSize:
    SMALL:
      EC2: t2.micro
      DB: db.t2.micro
    MEDIUM:
      EC2: t2.small
      DB: db.t2.small
    LARGE:
      EC2: t2.medium
      DB: db.t2.medium          

Resources:
  DB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB]
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region',  AmazonLinux2]
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: jobca-virginia
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash
            yum update -y
            yum install httpd mysql php-mysql -y
            amazon-linux-extras install php7.4
            systemctl enable httpd
            systemctl start httpd
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxf latest.tar.gz --strip 1
            rm -f latest.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  S3:
    Type: 'AWS::S3::Bucket'  # AWS names the bucket based by the stack name with random string
